### ISSUE TITLE
It doesn't work with the last raspberrymatic version

### ISSUE THREAD

**Issue by zioalex** [jens-maus/quickaccess#1]
Hi,
I tried the last addon version with the latest Raspberry Matic version. It seems that the installation process doesn't work properly because after the reboot I do not see the addon in the addon's list.

Other addons, like the watchdog and webmatic, are installed correctly.

Is there any way to debug it?
Cheers
Alessandro

**Comment by jens-maus** [comment]
Please try the latest 2.1b2 version just published.
